import {createRequire} from 'node:module';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1100},acceptDownloads:true});
page.setDefaultTimeout(15000);
page.on('console',m=>{if(m.type()==='error')console.log('Browser console:',m.text());});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('tmp/qa',{recursive:true});
await page.goto('http://127.0.0.1:4173');
await page.locator('.desk-result').first().waitFor();
await page.screenshot({path:'tmp/qa/desk-desktop.png',fullPage:true});
await page.locator('#rules-search').fill('snip');
await page.locator('.desk-result').filter({hasText:'Snip & Stitch'}).click();
await page.locator('#desk-rule-title').filter({hasText:'Snip & Stitch'}).waitFor();
assert.equal(await page.locator('#rules-search').inputValue(),'snip');
await page.getByRole('button',{name:'Save rule',exact:false}).click();
assert.equal(await page.locator('#bookmark').getAttribute('aria-pressed'),'true');
await page.screenshot({path:'tmp/qa/desk-rule-desktop.png',fullPage:true});
await page.goto('http://127.0.0.1:4173/#rules?saved=1');
await page.locator('.desk-result').filter({hasText:'Snip & Stitch'}).waitFor();
await page.goto('http://127.0.0.1:4173/#rules?q=zzzznothing');
await page.getByRole('heading',{name:'No entries found.'}).waitFor();
await page.goto('http://127.0.0.1:4173/#rules?category=Morale&q=enemy');
await page.locator('.desk-result').first().waitFor();
await page.locator('.desk-result').nth(1).click();
assert.equal(await page.locator('#rules-search').inputValue(),'enemy');
assert.equal(await page.locator('[data-topic="Morale"]').getAttribute('aria-pressed'),'true');
await page.goBack();
assert.equal(await page.locator('#rules-search').inputValue(),'enemy');
await page.goto('http://127.0.0.1:4173/#rule/slenderman-uncanny-dodge');
await page.locator('#desk-rule-title').filter({hasText:'Uncanny Dodge'}).waitFor();
await page.goto('http://127.0.0.1:4173/#rules');
await page.locator('#results').evaluate(el=>el.scrollTop=650);
const visible=page.locator('.desk-result').nth(5);
await visible.click();
const before=await page.locator('#results').evaluate(el=>el.scrollTop);
await page.locator('#bookmark').click();
assert.equal(await page.locator('#results').evaluate(el=>el.scrollTop),before);
await page.goto('http://127.0.0.1:4173/#subclasses');
await page.locator('.roster-row').first().waitFor();
assert.equal(await page.locator('.roster-row').count(),9);
await page.screenshot({path:'tmp/qa/roster-desktop.png',fullPage:true});
await page.locator('.roster-row').filter({hasText:'Sawbones'}).click();
await page.locator('.dossier-feature').first().waitFor();
assert.equal(await page.locator('.dossier-feature').count(),4);
await page.screenshot({path:'tmp/qa/dossier-desktop.png',fullPage:true});
await page.locator('#choose-class').click();
await page.locator('#subclass').waitFor();
assert.equal(await page.locator('#subclass').inputValue(),'Sawbones');
await page.goto('http://127.0.0.1:4173/#sheet');
await page.locator('#name').fill('Gravel');
await page.locator('#subclass').selectOption('Salt');
await page.locator('#level').fill('7');
await page.locator('#trait').selectOption('Lingerer');
await page.locator('#strength').fill('16');
await page.locator('#constitution').fill('14');
await page.locator('#hpMax').fill('64');
await page.locator('#tools').fill('Smith’s tools');
for(const s of ['Athletics','History','Insight','Perception','Survival'])await page.getByLabel(s,{exact:true}).check();
await page.locator('#resources').fill('Been here, done this: 12 / 17\nHard Road: 14 / 14');
await page.reload();await page.locator('#name').waitFor();assert.equal(await page.locator('#name').inputValue(),'Gravel');
await page.screenshot({path:'tmp/qa/sheet-desktop.png',fullPage:true});
let downloaded=page.waitForEvent('download');await page.locator('#download-pdf').click();await (await downloaded).saveAs('tmp/qa/gravel-editable.pdf');
downloaded=page.waitForEvent('download');await page.locator('#blank-pdf').click();await (await downloaded).saveAs('tmp/qa/universal-regression.pdf');
downloaded=page.waitForEvent('download');await page.locator('#export-json').click();await (await downloaded).saveAs('tmp/qa/gravel-backup.json');
await page.locator('#name').fill('Changed');
await page.locator('#import-file').setInputFiles('tmp/qa/gravel-backup.json');
await page.waitForFunction(()=>document.querySelector('#name')?.value==='Gravel');
await page.locator('#notes').fill('Long field note about the Company. '.repeat(200));
downloaded=page.waitForEvent('download');await page.locator('#download-pdf').click();await (await downloaded).saveAs('tmp/qa/long-notes.pdf');
await page.setViewportSize({width:390,height:844});
for(const [hash,file] of [['home','desk-mobile'],['rules','desk-index-mobile'],['subclasses','roster-mobile'],['class/Sawbones','dossier-mobile'],['sheet','sheet-mobile']]){
 await page.goto('http://127.0.0.1:4173/#'+hash);await page.waitForTimeout(200);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${hash} overflows mobile`);
 await page.screenshot({path:`tmp/qa/${file}.png`,fullPage:true});
}
await page.goto('http://127.0.0.1:4173/#rules?q=snip');
await page.locator('.desk-result').first().click();
await page.locator('#desk-rule-title').filter({hasText:'Snip & Stitch'}).waitFor();
assert(await page.locator('.desk-reading-pane').isVisible());
assert(!await page.locator('.desk-results-pane').isVisible());
await page.screenshot({path:'tmp/qa/desk-reader-mobile.png',fullPage:true});
await page.locator('#desk-back').click();
await page.locator('.desk-results-pane').waitFor({state:'visible'});
assert.equal(await page.locator('#rules-search').inputValue(),'snip');
assert.deepEqual(errors,[]);
await browser.close();
console.log('Browser QA passed: desk search/context/back navigation, bookmarks/scroll, legacy links, roster/dossier, mobile reader, unchanged character persistence/backup/PDF flows.');
