import {createRequire} from 'node:module';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1100},acceptDownloads:true});
page.setDefaultTimeout(15000);
page.on('console',m=>{if(m.type()==='error')console.log('Browser console:',m.text());});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('tmp/qa',{recursive:true});
const db=JSON.parse(await readFile('data/rules.json','utf8'));
await page.goto('http://127.0.0.1:4173');
await page.locator('.home-destinations').waitFor();
assert.equal(await page.locator('.home-destinations>a').count(),4);
await page.screenshot({path:'tmp/qa/home-desktop.png',fullPage:true});
await page.locator('#home-search').fill('snip');
await page.locator('#home-search').press('Enter');
await page.locator('.manual-entry summary').filter({hasText:'Snip & Stitch'}).click();
await page.locator('.manual-entry[open] [data-save]').click();
assert.equal(await page.locator('[data-save="sawbones-snip-stitch"]').getAttribute('aria-pressed'),'true');
assert.equal(await page.locator('#rules-search').inputValue(),'snip');
await page.screenshot({path:'tmp/qa/desk-rule-desktop.png',fullPage:true});
// Each chapter is independent of both previous searches and selected entries.
for(const category of [...new Set(db.records.map(r=>r.category))]){
 await page.locator('#rules-search').fill('snip');
 await page.locator(`[data-topic="${category}"]`).click();
 await page.waitForFunction(c=>document.querySelector('#manual-title')?.textContent===c,category);
 assert.equal(await page.locator('#rules-search').inputValue(),'');
 assert.equal(await page.locator(`[data-topic="${category}"]`).getAttribute('aria-current'),'page');
 const expected=db.records.filter(r=>r.category===category&&!(category==='Subclasses'&&r.overview)).map(r=>r.id);
 const actual=await page.locator('.manual-entry').evaluateAll(els=>els.map(el=>el.dataset.entry));
 assert.deepEqual(new Set(actual),new Set(expected),`${category} opens exactly its entries`);
 assert.equal(await page.locator('.manual-entry[open]').count(),0);
}
await page.locator('[data-topic="Morale"]').click();
await page.waitForFunction(()=>document.querySelector('#manual-title')?.textContent==='Morale');
await page.locator('.manual-entry summary').first().click();
await page.screenshot({path:'tmp/qa/desk-chapter-desktop.png',fullPage:true});
await page.locator('[data-expand="all"]').click();
assert.equal(await page.locator('.manual-entry[open]').count(),await page.locator('.manual-entry').count());
await page.locator('[data-expand="none"]').click();
assert.equal(await page.locator('.manual-entry[open]').count(),0);
await page.goto('http://127.0.0.1:4173/#rules?saved=1');
await page.locator('.manual-entry summary').filter({hasText:'Snip & Stitch'}).waitFor();
await page.reload();
await page.locator('.manual-entry summary').filter({hasText:'Snip & Stitch'}).waitFor();
await page.goto('http://127.0.0.1:4173/#rules?q=zzzznothing');
await page.getByRole('heading',{name:'No entries found.'}).waitFor();
await page.goto('http://127.0.0.1:4173/#rules?category=Morale&q=snip');
await page.locator('.manual-entry summary').filter({hasText:'Snip & Stitch'}).waitFor();
assert.equal(await page.locator('[data-topic][aria-current]').count(),0);
await page.locator('[data-topic="Traits"]').click();
await page.waitForFunction(()=>document.querySelector('#manual-title')?.textContent==='Traits');
await page.goBack();
await page.waitForFunction(()=>document.querySelector('#rules-search')?.value==='snip');
await page.goto('http://127.0.0.1:4173/#rule/slenderman-uncanny-dodge');
await page.locator('#entry-slenderman-uncanny-dodge[open]').waitFor();
await page.goto('http://127.0.0.1:4173/#rules?category=Morale&entry=sawbones-snip-stitch');
await page.locator('#entry-sawbones-snip-stitch[open]').waitFor();
assert.equal(await page.locator('#manual-title').textContent(),'Subclasses');
await page.goto('http://127.0.0.1:4173/#rule/sawbones-sawbones');
await page.locator('#entry-sawbones-sawbones[data-selected=true]').waitFor();
await page.goto('http://127.0.0.1:4173/#rule/not-an-entry');
await page.getByRole('heading',{name:'That rule could not be found.'}).waitFor();
await page.goto('http://127.0.0.1:4173/#rules');
await page.locator('.manual-directory').waitFor();
await page.screenshot({path:'tmp/qa/desk-desktop.png',fullPage:true});
await page.setViewportSize({width:2200,height:1200});
await page.goto('http://127.0.0.1:4173/#subclasses');
await page.locator('.roster-page').waitFor();
assert.equal(Math.round((await page.locator('.roster-page').boundingBox()).width),1898);
await page.screenshot({path:'tmp/qa/roster-wide.png',fullPage:true});
await page.setViewportSize({width:1440,height:1100});
await page.goto('http://127.0.0.1:4173/#subclasses');
await page.locator('.roster-row').first().waitFor();
assert.equal(await page.locator('.roster-row').count(),9);
await page.screenshot({path:'tmp/qa/roster-desktop.png',fullPage:true});
await page.locator('.roster-row').filter({hasText:'Sawbones'}).click();
await page.locator('.dossier-feature').first().waitFor();
assert.equal(await page.locator('.dossier-feature').count(),4);
await page.screenshot({path:'tmp/qa/dossier-desktop.png',fullPage:true});
await page.locator('#choose-class').click();
await page.locator('#subclass').waitFor();
assert.equal(await page.locator('#subclass').inputValue(),'Sawbones');
await page.goto('http://127.0.0.1:4173/#sheet');
await page.locator('#name').fill('Gravel');
await page.locator('#subclass').selectOption('Salt');
await page.locator('#level').fill('7');
await page.locator('#trait').selectOption('Lingerer');
await page.locator('#strength').fill('16');
await page.locator('#constitution').fill('14');
await page.locator('#hpMax').fill('64');
await page.locator('#tools').fill('Smith’s tools');
for(const s of ['Athletics','History','Insight','Perception','Survival'])await page.getByLabel(s,{exact:true}).check();
await page.locator('#fightingStyle').fill('Defense (+1 AC while wearing armor)');
await page.locator('#masteries').fill('Longsword / Sap; Longbow / Slow');
await page.locator('#feats').fill('Level 4: ability score improvement');
await page.locator('#secondWind').fill('0');
await page.locator('details').filter({has:page.locator('#attack1Name')}).locator('summary').click();
await page.locator('#attack1Name').fill('Longsword');
await page.locator('.conditional-group').filter({has:page.locator('#weapon1Mode')}).locator('summary').click();
await page.locator('[data-weapon-preset="1"]').selectOption('Longsword');
assert.equal(await page.locator('#weapon1Dice').inputValue(),'1d8/1d10 slashing');
await page.locator('#weapon1Hands').selectOption('Two');
assert.match(await page.locator('#equipment-effects').innerText(),/1d10 slashing/);
await page.locator('#weapon1Hands').selectOption('One');
await page.locator('#attack1Bonus').fill('+6');
await page.locator('#attack1Damage').fill('1d8+3 slashing');
await page.locator('#armorType').selectOption('Plate');
await page.locator('#shieldEquipped').selectOption('Yes');
await page.locator('#styleRule').selectOption('Defense');
assert.match(await page.locator('#equipment-effects').innerText(),/AC 21/);
await page.locator('.conditional-group').filter({has:page.locator('#houseRules')}).locator('summary').click();
await page.locator('#houseRules').selectOption('On');
await page.locator('#overrideAC').fill('0');
assert.match(await page.locator('#equipment-effects').innerText(),/AC 0/);
await page.locator('#houseRules').selectOption('Off');
assert.match(await page.locator('#equipment-effects').innerText(),/AC 21/);
await page.locator('#resources').fill('Been here, done this: 12 / 17\nHard Road: 14 / 14');
await page.reload();await page.locator('#name').waitFor();assert.equal(await page.locator('#name').inputValue(),'Gravel');assert.equal(await page.locator('#fightingStyle').inputValue(),'Defense (+1 AC while wearing armor)');assert.equal(await page.locator('#attack1Name').inputValue(),'Longsword');
await page.locator('.form-section').filter({has:page.locator('#armorType')}).screenshot({path:'tmp/qa/equipment-web.png'});
await page.screenshot({path:'tmp/qa/sheet-desktop.png',fullPage:true});
let downloaded=page.waitForEvent('download');await page.locator('#download-pdf').click();await (await downloaded).saveAs('tmp/qa/gravel-editable.pdf');
downloaded=page.waitForEvent('download');await page.locator('#blank-pdf').click();await (await downloaded).saveAs('tmp/qa/universal-regression.pdf');
downloaded=page.waitForEvent('download');await page.locator('#export-json').click();await (await downloaded).saveAs('tmp/qa/gravel-backup.json');
await page.locator('#name').fill('Changed');
await page.locator('#import-file').setInputFiles('tmp/qa/gravel-backup.json');
await page.waitForFunction(()=>document.querySelector('#name')?.value==='Gravel');
await page.locator('#notes').fill('Long field note about the Company. '.repeat(200));
downloaded=page.waitForEvent('download');await page.locator('#download-pdf').click();await (await downloaded).saveAs('tmp/qa/long-notes.pdf');
await page.setViewportSize({width:390,height:844});
for(const [hash,file] of [['home','desk-mobile'],['rules','desk-index-mobile'],['subclasses','roster-mobile'],['class/Sawbones','dossier-mobile'],['sheet','sheet-mobile']]){
 await page.goto('http://127.0.0.1:4173/#'+hash);await page.waitForTimeout(200);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${hash} overflows mobile`);
 await page.screenshot({path:`tmp/qa/${file}.png`,fullPage:true});
}
await page.goto('http://127.0.0.1:4173/#rules?q=snip');
await page.locator('.manual-entry summary').filter({hasText:'Snip & Stitch'}).click();
assert(await page.locator('#entry-sawbones-snip-stitch[open]').isVisible());
assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'tmp/qa/desk-reader-mobile.png',fullPage:true});
await page.locator('#desk-mobile-topic').selectOption('Morale');
await page.waitForFunction(()=>document.querySelector('#manual-title')?.textContent==='Morale');
assert.equal(await page.locator('#rules-search').inputValue(),'');
assert.equal(await page.locator('.manual-entry').count(),db.records.filter(r=>r.category==='Morale').length);
await page.locator('.manual-entry summary').first().focus();
await page.keyboard.press('Enter');
await page.locator('.manual-entry[open]').waitFor();
assert.deepEqual(errors,[]);
await browser.close();
console.log('Browser QA passed: homepage navigation/search, all nine chapter targets, global search, inline reading, saved persistence, legacy/mismatched deep links, wide roster, mobile and keyboard navigation, unchanged character persistence/backup/PDF flows.');
