import {createRequire} from 'node:module';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.PLAYWRIGHT_PATH||'playwright');
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const page=await browser.newPage({viewport:{width:1440,height:1100},acceptDownloads:true});
page.setDefaultTimeout(15000);
page.on('console',m=>{if(m.type()==='error')console.log('Browser console:',m.text());});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('tmp/qa',{recursive:true});
await page.goto('http://127.0.0.1:4173');
await page.locator('.chapter').first().waitFor();
await page.screenshot({path:'tmp/qa/home-desktop.png',fullPage:true});
await page.locator('#home-search').fill('snip');
await page.waitForURL('**/#rules?q=snip');
await page.getByRole('heading',{name:'Snip & Stitch'}).waitFor();
await page.getByRole('heading',{name:'Snip & Stitch'}).click();
await page.getByRole('button',{name:'Save rule',exact:false}).click();
assert.equal(await page.locator('#bookmark').getAttribute('aria-pressed'),'true');
await page.screenshot({path:'tmp/qa/rule-desktop.png',fullPage:true});
await page.goto('http://127.0.0.1:4173/#rules?saved=1');
await page.getByRole('heading',{name:'Snip & Stitch'}).waitFor();
await page.goto('http://127.0.0.1:4173/#rules?q=zzzznothing');
await page.getByRole('heading',{name:'No entries found.'}).waitFor();
await page.goto('http://127.0.0.1:4173/#rules?q=morale');
await page.locator('#results .result-row').first().waitFor();
await page.screenshot({path:'tmp/qa/index-desktop.png',fullPage:true});
await page.goto('http://127.0.0.1:4173/#sheet');
await page.locator('#name').fill('Gravel');
await page.locator('#subclass').selectOption('Salt');
await page.locator('#level').fill('7');
await page.locator('#trait').selectOption('Lingerer');
await page.locator('#strength').fill('16');
await page.locator('#constitution').fill('14');
await page.locator('#hpMax').fill('64');
await page.locator('#tools').fill('Smith’s tools');
for(const s of ['Athletics','History','Insight','Perception','Survival'])await page.getByLabel(s,{exact:true}).check();
await page.locator('#resources').fill('Been here, done this: 12 / 17\nHard Road: 14 / 14');
await page.reload();await page.locator('#name').waitFor();assert.equal(await page.locator('#name').inputValue(),'Gravel');
await page.screenshot({path:'tmp/qa/sheet-desktop.png',fullPage:true});
let downloaded=page.waitForEvent('download');await page.locator('#download-pdf').click();await (await downloaded).saveAs('tmp/qa/gravel-editable.pdf');
downloaded=page.waitForEvent('download');await page.locator('#blank-pdf').click();await (await downloaded).saveAs('output/pdf/black-company-universal-editable.pdf');
downloaded=page.waitForEvent('download');await page.locator('#export-json').click();await (await downloaded).saveAs('tmp/qa/gravel-backup.json');
await page.locator('#name').fill('Changed');
await page.locator('#import-file').setInputFiles('tmp/qa/gravel-backup.json');
await page.waitForFunction(()=>document.querySelector('#name')?.value==='Gravel');
await page.locator('#notes').fill('Long field note about the Company. '.repeat(200));
downloaded=page.waitForEvent('download');await page.locator('#download-pdf').click();await (await downloaded).saveAs('tmp/qa/long-notes.pdf');
await page.setViewportSize({width:390,height:844});
for(const [hash,file] of [['home','home-mobile'],['rules','index-mobile'],['sheet','sheet-mobile']]){
 await page.goto('http://127.0.0.1:4173/#'+hash);await page.waitForTimeout(200);
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${hash} overflows mobile`);
 await page.screenshot({path:`tmp/qa/${file}.png`,fullPage:true});
}
assert.deepEqual(errors,[]);
await browser.close();
console.log('Browser QA passed: search, bookmarks, empty state, persistence, backup roundtrip, editable/blank/overflow PDFs, and mobile widths.');
